### PR TITLE
Delete vcf harmonization

### PR DESCRIPTION
**Pull request by allaway**
I think that this subfolder can be deleted as it's now all in gene-variant workflow subfolder.

### CODE REVIEW

**Comment by sgosline** [comment]
I haven't tested the new version extensively - @jaybee84 or @allaway can you confirm that the new WF does the same thing before deleting it?

**Comment by allaway** [comment]
Hmm, yeah, maybe it's not ready...

Latest run of the wf: ```ERROR [job run-vep] Job error:
Error collecting output for parameter 'maf-file':
steps/run-vep.cwl:46:7: Did not find output file with glob pattern: '[u'*.maf']'```

**Comment by sgosline** [comment]
Hahaha, ok Baby steps.

**Comment by sgosline** [comment]
Ok, i think it's safe to do this now!

**Pull request merged**
