### PR TITLE
Deepvar workflow

### PR DESCRIPTION
**Pull request by sgosline**
Got deepvar working in CWL form from bam to VCF. still needs to add in the MAF component, which I hope to do soon, but wanted to get this PR started. Can one of you review it to see if it makes sense?

### CODE REVIEW

**Comment by allaway** [comment]
seems to make sense so far. I couldn't quite tell but it looks like you are planning on storing the vcf from deepvariant as well, which i think is a good idea. 

I wonder if it is worth leaving the vep/vcf2maf step as a separate workflow, since we already have that as an independent workflow? it's a pretty beefy workflow as it is.

**Comment by allaway** [comment]
FWIW - i did not find it a pain to run deepvariant and vcf2maf as separate steps (even though one was not a workflow at the time)

**Comment by sgosline** [comment]
I'm not worried so much about running as propagating the annotations - did you find *that* to be a pain?

**Comment by allaway** [comment]
Well, it was a bit of a pain, but only because the first step was not
workflow-ized. For a workflow I assume we'd pass the annotations back to
the vcf at the end of the workflow, right?

**Comment by allaway** [comment]
This is also the wrong place to bring this up but i am wondering if there
are any better options for vcf to maf. vep+the way it is implemented in
that container/workflow is so inefficient and slow

**Comment by sgosline** [comment]
Ok. I'm working on getting the vcf's uploaded/annotated, and then doing the mafs later on. @jaybee84 has suggested genome nexus as a way to move the annotation forward, so we can definitely do that in the future if it's modular enough. maybe file an issue though :)

**Pull request merged**
